### ISSUE TITLE
Values in root chart using yaml variables are not overwritable

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/helm-charts#141]
Values like `clusterName` and `clusterDomain` and `trustBundle` are not overwriteable.

https://github.com/spiffe/helm-charts/blob/main/charts/spire/values.yaml#L14-L17

When defining different values for these, they are still using the values as defined in the main chart.

e.g.:

```yaml
spire-server:
  clusterName: my-cluster
  clusterDomain: my-cluster-domain.com
  trust-bundle: my-trust-domain
```

The solution can probably be found in https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
