### ISSUE TITLE
Running with podSecurityContext as shown in production example fails spire-server bootup

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/helm-charts#142]
Running spire-server with following as shown in production example fails:

```yaml
spire-server:
  securityContext:
    runAsNonRoot: true
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
```

See spire-server log:

```shell
time="2023-03-20T12:39:20Z" level=error msg="Fatal run error" error="datastore-sql: unable to open database file: permission denied"
time="2023-03-20T12:39:20Z" level=error msg="Server crashed" error="datastore-sql: unable to open database file: permission denied"
```
