### ISSUE TITLE
Values Profiles

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts#146]
Having a set of prebuilt values files (see examples) for use with various production deployments may prove too burdensome for the end users to be able to juggle.

I'm proposing a possible change. First we come up with an api like:

```yaml
global:
  spire:
    # - Select a list of predefined sets of values to automatically default to.
    tags:
    - production
    - expose-oidc-ingress-nginx
    - expose-spire-server-ingress-nginx
```

What settings are for what tags are not really important at the moment.

Each chart would look for a set of tags that it supports and use the merge function to add some extra defaults into values, preferring what the user specified over its own values.
