### ISSUE TITLE
Charts don't support configuring to not run as root

### ISSUE THREAD

**Issue by keeganwitt** [spiffe/helm-charts#177]
Both the agent and server YAML files have no templating to support running as a non-root user.

**Comment by kfox1111** [comment]
The server can run restricted. We're testing against it with each PR:
https://github.com/spiffe/helm-charts/blob/main/examples/production/values.yaml#L31-L52

The agent needs to be root so it can probe the unix socket for the user at the other end of the socket. It can't run as nonroot and function properly.

**Comment by kfox1111** [comment]
Please reopen if there is something that you need that still isn't handled.

**Comment by keeganwitt** [comment]
Sorry, I should have been clearer about how I'd been doing this. It's not perfect, but it does reduce the risk surface a little. Doing this isn't possible with the chart.

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  namespace: {{ $.Release.Namespace }}
  labels:
    app: agent
spec:
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      annotations:
      labels:
        app: agent
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      initContainers:
        - name: chmod-socket-directory
          image: busybox
          command: [ "sh", "-c", "chown -R 10000:10000 /run/spire/socket" ]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: agent-socket
              mountPath: /run/spire/socket
```
