### ISSUE TITLE
Make projected service account tokens an opt-in feature

### ISSUE THREAD

**Issue by drewwells** [spiffe/helm-charts#298]
Projected Service Account Tokens are a very new feature, as [mentioned here](https://spiffe.io/docs/latest/deploying/configuring/#projected-service-account-tokens). As a result, many users can not use this feature in cases where they're using k8s like EKS.

There should be a flag to turn off the service account verification. Is there a cli arg that needs to be set? I believe it should be possible to sniff out apicapabilities to enable this feature when it is available in the cluster.

**Comment by kfox1111** [comment]
Its been marked stable (and enabled by default) in upstream Kubernetes since v1.20.0 (Dec 8, 2020). Is it really disabled by default still in EKS? I'm having a hard time finding documentation on it in EKS.

**Comment by kfox1111** [comment]
AKS made it available (Beta feature?) in 02-24-2020: https://github.com/Azure/AKS/releases/tag/2020-02-24

**Comment by drewwells** [comment]
I stand corrected, EKS seems to support it even though they don't advertise   
```
vault-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  7200
```

It still raises a problem around setting `kube-apiserver` flags. We can't set flags on our controlplane in EKS. Is there a workaround for this?  I'm not actually clear what this is doing, is `spire-agent` taking over service account token creation for the cluster, can we disable that?
```
spec:
  containers:
    - command:
        - kube-apiserver
        - --api-audiences=api,spire-server
        - --service-account-issuer=api,spire-agent
        - --service-account-key-file=/run/config/pki/sa.pub
        - --service-account-signing-key-file=/run/config/pki/sa.key
```

**Comment by kfox1111** [comment]
Shouldn't need to do that I think....

If you try to load something like this on your cluster, without changes, does it work:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  serviceAccountName: default
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 7200
          audience: vault
```

**Comment by marcofranssen** [comment]
I can confirm Projected Service Account tokens do work on EKS. have been using it for 1,5 years at least. I think I started with EKS 1.22 version. Now on EKS 1.25. haven't seen issues with PSAT. I'm not setting those API flags on EKS, but it still works and is able to do the attestation. 

Let me know if all works for you by just plain installing the helm-chart.

**Comment by kfox1111** [comment]
We may want to have the spire folks update the documentation since it was accurate when it was written, but is probably less of a concern today.

**Comment by drewwells** [comment]
Asking from above again, is this mandatory? I am seeing all the `wait-for-it` init containers failing even though spire-server-0 seems to be up and ready

```
spec:
  containers:
    - command:
        - kube-apiserver
        - --api-audiences=api,spire-server
        - --service-account-issuer=api,spire-agent
        - --service-account-key-file=/run/config/pki/sa.pub
        - --service-account-signing-key-file=/run/config/pki/sa.key
        ```
