### ISSUE TITLE
Federated tokens error with `no keys found for trust domain`

### ISSUE THREAD

**Issue by drewwells** [spiffe/helm-charts#364]
Two spire-servers are federated:

```
 k --context box-3 exec -n spire-server -c spire-server spire-server-0 -- spire-server federation list                      box-4
Found 1 federation relationship

Trust domain              : box-4.example.com
Bundle endpoint URL       : https://spire-box-4.eng.test.example.com/
Bundle endpoint profile   : https_web
```
jwt has federatedWith on it (was this property really necessary?  It makes me 😢 )
```
spire-server entry show -spiffeID spiffe://box-4.example.com/ns/dwells/sa/dwells-rc-realm-client
Found 1 entry
Entry ID         : 6f1f9077-f2dc-4274-9fd5-520d386d2116
SPIFFE ID        : spiffe://box-4.example.com/ns/dwells/sa/dwells-rc-realm-client
Parent ID        : spiffe://box-4.example.com/spire/agent/k8s_psat/example-cluster/ff93872d-791f-4bf3-a532-475775d03d3e
Revision         : 0
X509-SVID TTL    : default
JWT-SVID TTL     : default
Selector         : k8s:pod-uid:558c1907-db61-4510-8ff2-99734b73245a
FederatesWith    : box-3.example.com
```

Tokens can not be verified by agent running on box-4
```
time="2023-06-22T05:53:55Z" level=warning msg="Failed to validate JWT" audience=us-com-1 error="no keys found for trust domain \"box-4.example.com\"" method=ValidateJWTSVID pid=28129 service=WorkloadAPI subsystem_name=endpoints
```

**Comment by drewwells** [comment]
CR. I did not manually put bundle in, that would be very hard to automate. I see it successfully claiming to pull public keys from federated ingress. However, the public keys are identical for local and federated endpoint.
```
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterFederatedTrustDomain
metadata:
  name: spire.box-3
spec:
  bundleEndpointProfile:
    type: https_web
  bundleEndpointURL: https://spire.box-3.eng.test.example.com/
  trustDomain: box-3.example.com
  ```

```
****************************************
* example.com
****************************************
-----BEGIN CERTIFICATE-----
MIIBbzCCARWgAwIBAgIRAJyoBOeTGFo/xKYwXHSSim0wCgYIKoZIzj0EAwIwFzEV
...
FAIgV5lPF/+EbeS+REVwx6BAOWXTA2zshdh48WFGu46do8I=
-----END CERTIFICATE-----

****************************************
* box-4.example.com
****************************************
-----BEGIN CERTIFICATE-----
MIIBbzCCARWgAwIBAgIRAJyoBOeTGFo/xKYwXHSSim0wCgYIKoZIzj0EAwIwFzEV
...
FAIgV5lPF/+EbeS+REVwx6BAOWXTA2zshdh48WFGu46do8I=
-----END CERTIFICATE-----
```
