### ISSUE TITLE
cert manager upstream has inconsistent casing

### ISSUE THREAD

**Issue by faisal-memon** [spiffe/helm-charts#418]
Note the mix of snake and camel case. Should be all camel case.

```
  certManager:
    enabled: false
    rbac:
      create: true
    # -- Defaults to the release name, override if CA is provided outside of the chart
    issuer_name: ""
    issuer_kind: "Issuer"
    issuer_group: "cert-manager.io"
    # -- Specify to use a namespace other then the one the chart is installed into
    namespace: ""
    kube_config_file: ""

    ca:
      # -- Creates a Cert-Manager CA
      create: false
      # -- Duration of the CA. Defaults to 10 years.
      duration:  87600h
      privateKey:
```
